---
apiVersion: v1
kind: Template
metadata:
  name: cronjob-prune-projects
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${NAME}
    labels:
      template: cronjob-prune-projects
  spec:
    lookupPolicy:
      local: true
- kind: BuildConfig
  apiVersion: v1
  metadata:
    annotations:
      description: Defines how to build the application
    name: ${NAME}
    labels:
      template: cronjob-prune-projects
  spec:
    completionDeadlineSeconds: 1800
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:${TAG}
    runPolicy: Serial
    source:
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: "${CONTEXT_DIR}"
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: "${BASE_IMAGE}"
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: prune-ocp-projects
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Git source URL for application
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/redhat-cop/openshift-management
- description: Path within Git repository to build; empty for root of repository
  name: CONTEXT_DIR
  value: "images/prune-ocp-projects"
- description: Base image for the buils
  name: BASE_IMAGE
  required: true
  value: "centos:7"
- description: The tag for the iamge
  displayName: Image Tag
  name: TAG
  required: true
  value: latest
